baseURL: https://busie-portfolio.netlify.app/
languageCode: en-us
title: Portfolio Website for Busie
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Let's start!
    subtitle: |-
      I am a Masters in Financial Analysis student 
      at London Business School.
    title: Hi, my name is Busie. Welcome to my portfolio!
  blog: {}
  contact:
    address: 
      - city: London,
        country: United Kingdom
        street: Regents Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: bdhlodhlo.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (000) 000 0000
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Busie
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/busiedlodlo/
      - icon: fa-github
        label: GitHub
        url: https://github.com/busieddhlodhlo/
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/sibusisiwe-dhlodhlo/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Let's start!
        url: '#'
#    button2:
#      - name: Background
#        url: blogs
    links:
      - name: Home
        url: '#'
      - name: Explore
        url: blogs
#      - name: Generic Blog
#        url: blogs/ipsum
#      - name: Elements
#        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: small.jpg
        subtitle: Short biography
        title: About me
        url: blogs/aliquam
      - image: padenga.png
        subtitle: I co-authored a research report on a publicly listed company operating in the aquaculture industry.
        title: CFA Equity Research Challenge
        url: https://drive.google.com/file/d/1vtOgU4zUJPehAopv1Jj_XWCsiXAxgvxG/view?usp=sharing
      - image: riskret.jpg
        subtitle: Looking into the JDIA risk return metrics.
        title: Dow Jones Risk Return
        url: https://busie-portfolio.netlify.app/blogs/risk_return/
      - image: bikes.jpg
        subtitle: An analysis of Tfl bike sharing in the UK.
        title: UK Tfl bike rentals
        url: blogs/bikes
      - image: plain.jpg
        subtitle: My face on the university magazine cover page.
        title: Once upon a moment of fame!
        url: http://solusi.ac.zw/wp-content/uploads/2018/12/Solusi-Orb-Vol-1-Issue-2.pdf    
      - image: write.jpg
        subtitle: Using words to shape thoughts on Medium
        title: Read my thoughts?
        url: https://medium.com/@busiedlodlo/

  two:
    buttonText: Get Started
    enable: yes
    subtitle: "I come from Plumtree, a small town in Zimbabwe. \r\n  I studied Finance with Accounting Minor at Solusi University and went on to sit for CFA Level One soon after graduation. \r\n  During my undergraduate term, I was part of my schoolâ€™s CFA Equity Research Challenge Team. \r\n  We researched on a Zimbabwean-domiciled business operating in the aquaculture industry and presented an investment recommendation before a panel of judges. \r\n  My first post-graduation job was in Alternative Investments before which I had worked in the NPO sector while studying simultaneously. \r\n  I also worked in an agricultural engineering company where I helped create financial products for its clients. \r\n  During that time I volunteered at a local home-school where I had a fulfilling experience learning and reflecting with young learners. \r\n  I would like to work in Investment Management spaces where I can contribute to improving the livelihoods of many after completing the Masters programme at LBS."
    title: About me
    url: blogs
