baseURL: https://busie-portfolio.netlify.app/
languageCode: en-us
title: Portfolio Website for Busie
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Let's start!
    subtitle: |-
      I am a Masters in Financial Analysis student 
      at London Business School.
    title: Hi, my name is Busie. Welcome to my portfolio!
  blog: {}
  contact:
    address: 
      - city: London,
        country: United Kingdom
        street: Regents Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: bdhlodhlo.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (000) 000-0000 x1234
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Busie
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/busiedlodlo/
      - icon: fa-github
        label: GitHub
        url: https://github.com/busieddhlodhlo/
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/sibusisiwe-dhlodhlo/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Let's start!
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
#      - name: Generic Blog
#        url: blogs/ipsum
#      - name: Elements
#        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: beach.jpg
        subtitle: Short biography
        title: About me
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Risk Return od DJIA stocks
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
#      - image: pic05.jpg
#        subtitle: Ipsum Dolor Sit Amet
#        title: Consequat
#        url: blogs/ipsum
#      - image: pic06.jpg
#        subtitle: Feugiat Amet Tempus
#        title: Etiam
#        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "I come from Plumtree, a small town in Zimbabwe. \r\n  I studied Finance with Accounting Minor at Solusi University and went on to sit for CFA Level One soon after graduation. \r\n  During my undergraduate term, I was part of my schoolâ€™s CFA Equity Research Challenge Team. \r\n  We researched on a Zimbabwean-domiciled business operating in the aquaculture industry and presented an investment recommendation before a panel of judges. \r\n  My first post-graduation job was in Alternative Investments before which I had worked in the NPO sector while studying simultaneously. \r\n  I also worked in an agricultural engineering company where I helped create financial products for its clients. \r\n  During this time I volunteered at a local home-school where I had a fulfilling time learning and reflecting with young learners. \r\n  I would like to work in Investment Management spaces where I can contribute to improving the livelihoods of many after completing the Masters programme at LBS."
    title: About me
    url: blogs
